applications:
  - application: "RetirementCalculator"
    description: "RetirementCalculator"
    owner: "MDALBIN"
    namingConventions:
      - "EBU."
      - "LINPUT"
  - application: "GenApp"
    description: "GenApp"
    owner: "DBEHM"
    namingConventions:
      - "LG......"
      - "SOA....."
      - "POL....."
      - "SSMAP..."
  - application: "CBSA"
    description: "CBSA"
    owner: "MDALBIN"
    namingConventions:
      - "ABN....."
      - "ACC....."
      - "BAN....."
      - "BNK....."
      - "CON....."
      - "CRD....."
      - "CRE....."
      - "CUS....."
      - "DBC....."
      - "DEL....."
      - "DPA....."
      - "GET....."
      - "INQ....."
      - "PRO....."
      - "UPD....."
      - "XFR....."
      - "ZUN....."